"""Initial migration

Revision ID: 225e342b5118
Revises: 
Create Date: 2025-08-17 10:45:12.202157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225e342b5118'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###