"""add_missing_audit_action_enum_values

Revision ID: 3c928ce023c5
Revises: f5f669fde2b8
Create Date: 2025-08-21 18:39:43.233729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c928ce023c5'
down_revision = 'f5f669fde2b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###