"""add_payment_tracking_fields_to_user_packages

Revision ID: 3d19930024a9
Revises: fdd1912253fa
Create Date: 2025-08-22 18:16:07.904868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d19930024a9'
down_revision = 'fdd1912253fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_package_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('approved', 'rejected', name='paymentapprovalaction'), nullable=False),
    sa.Column('action_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name=op.f('fk_payment_approvals_admin_id_users')),
    sa.ForeignKeyConstraint(['user_package_id'], ['user_packages.id'], name=op.f('fk_payment_approvals_user_package_id_user_packages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_approvals'))
    )
    op.create_index(op.f('ix_payment_approvals_id'), 'payment_approvals', ['id'], unique=False)
    op.drop_index('ix_bookings_booking_date', table_name='bookings')
    op.drop_index('ix_bookings_class_status', table_name='bookings')
    op.drop_index('ix_bookings_user_status', table_name='bookings')
    op.drop_index('ix_class_instances_datetime_status', table_name='class_instances')
    op.drop_index('ix_class_instances_end_datetime', table_name='class_instances')
    
    # Create the enum type before adding the column
    op.execute("CREATE TYPE userpackagepaymentstatus AS ENUM ('pending_approval', 'approved', 'rejected')")
    op.add_column('user_packages', sa.Column('payment_status', sa.Enum('pending_approval', 'approved', 'rejected', name='userpackagepaymentstatus'), nullable=False))
    op.add_column('user_packages', sa.Column('payment_method', sa.Enum('CREDIT_CARD', 'CASH', 'BANK_TRANSFER', 'PAYPAL', 'STRIPE', name='paymentmethod'), nullable=False))
    op.add_column('user_packages', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('user_packages', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_packages', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('user_packages', sa.Column('payment_reference', sa.String(), nullable=True))
    op.add_column('user_packages', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.drop_index('ix_user_packages_user_active', table_name='user_packages')
    op.drop_index('ix_user_packages_user_status_expiry', table_name='user_packages')
    op.create_foreign_key(op.f('fk_user_packages_approved_by_users'), 'user_packages', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_packages_approved_by_users'), 'user_packages', type_='foreignkey')
    op.create_index('ix_user_packages_user_status_expiry', 'user_packages', ['user_id', 'status', 'expiry_date'], unique=False)
    op.create_index('ix_user_packages_user_active', 'user_packages', ['user_id', 'is_active'], unique=False)
    op.drop_column('user_packages', 'admin_notes')
    op.drop_column('user_packages', 'payment_reference')
    op.drop_column('user_packages', 'rejection_reason')
    op.drop_column('user_packages', 'approved_at')
    op.drop_column('user_packages', 'approved_by')
    op.drop_column('user_packages', 'payment_method')
    op.drop_column('user_packages', 'payment_status')
    op.execute("DROP TYPE IF EXISTS userpackagepaymentstatus")
    op.execute("DROP TYPE IF EXISTS paymentapprovalaction")
    op.create_index('ix_class_instances_end_datetime', 'class_instances', ['end_datetime'], unique=False)
    op.create_index('ix_class_instances_datetime_status', 'class_instances', ['start_datetime', 'status'], unique=False)
    op.create_index('ix_bookings_user_status', 'bookings', ['user_id', 'status'], unique=False)
    op.create_index('ix_bookings_class_status', 'bookings', ['class_instance_id', 'status'], unique=False)
    op.create_index('ix_bookings_booking_date', 'bookings', ['booking_date'], unique=False)
    op.drop_index(op.f('ix_payment_approvals_id'), table_name='payment_approvals')
    op.drop_table('payment_approvals')
    # ### end Alembic commands ###