"""Add audit_logs table

Revision ID: 5db627ab5e5c
Revises: b266ea00895e
Create Date: 2025-08-20 22:57:48.642858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db627ab5e5c'
down_revision = 'b266ea00895e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###