"""

Revision ID: 853ae1dbca46
Revises: 15e0e7d698c7
Create Date: 2025-08-23 13:47:11.978029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853ae1dbca46'
down_revision = '15e0e7d698c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payment_approvals_bulk_operation', table_name='payment_approvals')
    op.drop_index('idx_payment_approvals_ip_address', table_name='payment_approvals')
    op.add_column('user_packages', sa.Column('authorized_by', sa.Integer(), nullable=True))
    op.add_column('user_packages', sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_packages', sa.Column('payment_confirmed_by', sa.Integer(), nullable=True))
    op.add_column('user_packages', sa.Column('payment_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_packages', sa.Column('payment_confirmation_reference', sa.String(), nullable=True))
    op.drop_index('idx_user_packages_approval_deadline', table_name='user_packages')
    op.drop_index('idx_user_packages_approval_status', table_name='user_packages')
    op.drop_index('idx_user_packages_payment_status_approval', table_name='user_packages')
    op.create_foreign_key(op.f('fk_user_packages_payment_confirmed_by_users'), 'user_packages', 'users', ['payment_confirmed_by'], ['id'])
    op.create_foreign_key(op.f('fk_user_packages_authorized_by_users'), 'user_packages', 'users', ['authorized_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_packages_authorized_by_users'), 'user_packages', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_packages_payment_confirmed_by_users'), 'user_packages', type_='foreignkey')
    op.create_index('idx_user_packages_payment_status_approval', 'user_packages', ['payment_status', 'approval_status'], unique=False)
    op.create_index('idx_user_packages_approval_status', 'user_packages', ['approval_status'], unique=False)
    op.create_index('idx_user_packages_approval_deadline', 'user_packages', ['approval_deadline'], unique=False)
    op.drop_column('user_packages', 'payment_confirmation_reference')
    op.drop_column('user_packages', 'payment_confirmed_at')
    op.drop_column('user_packages', 'payment_confirmed_by')
    op.drop_column('user_packages', 'authorized_at')
    op.drop_column('user_packages', 'authorized_by')
    op.create_index('idx_payment_approvals_ip_address', 'payment_approvals', ['ip_address'], unique=False)
    op.create_index('idx_payment_approvals_bulk_operation', 'payment_approvals', ['bulk_operation_id'], unique=False)
    # ### end Alembic commands ###