"""Create audit_logs table with proper imports

Revision ID: f05ae53e1709
Revises: 5db627ab5e5c
Create Date: 2025-08-20 22:59:09.338857

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f05ae53e1709"
down_revision = "5db627ab5e5c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "LOGIN_SUCCESS",
                "LOGIN_FAILED",
                "LOGOUT",
                "TOKEN_REFRESH",
                "PASSWORD_CHANGE",
                "PASSWORD_RESET_REQUEST",
                "PASSWORD_RESET_SUCCESS",
                "USER_CREATE",
                "USER_UPDATE",
                "USER_DELETE",
                "USER_ACTIVATE",
                "USER_DEACTIVATE",
                "EMAIL_VERIFICATION",
                "RATE_LIMIT_EXCEEDED",
                "SUSPICIOUS_ACTIVITY",
                "FORCE_LOGOUT_ALL",
                "TWO_FA_ENABLE",
                "TWO_FA_DISABLE",
                "ADMIN_LOGIN",
                "SYSTEM_CONFIG_CHANGE",
                "BULK_OPERATION",
                "DATA_EXPORT",
                "DATA_ANONYMIZATION",
                "GDPR_REQUEST",
                name="auditactiontype",
            ),
            nullable=False,
        ),
        sa.Column("resource_type", sa.String(length=50), nullable=True),
        sa.Column("resource_id", sa.Integer(), nullable=True),
        sa.Column(
            "security_level",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="securitylevel"),
            nullable=True,
        ),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=36), nullable=True),
        sa.Column("success", sa.String(length=10), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_logs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
